#!/usr/bin/env python3
"""ARCHIVED — DO NOT RUN AGAINST THE CURRENT PROJECT. Kept for reference only.

This script belongs to the V1 arena pipeline: it composites a 1200x905
frame.webp. The shipped arena has since been replaced by the V2 art at
3312x1896 (the fal.ai upscale — see src/game.js's W/H and ART_V2_SCALE), and
public/arena/frame.webp is now generated by the V2 pipeline, not by this file.

Running it as written would silently replace the production 3312x1896 arena
with a 1200x905 image, invalidating every hand-measured pixel bound in
game.js (FX0/FY0/FX1/FY1, the goal mouth, the score-digit slots) AND poisoning
the seven other scripts that read frame.webp as their own input
(bake_mobile_frame, bake_hex_timer, bake_score_digits, bake_handoff_mask,
bake_waiting_label, bake_chat_rock, bake_curling_arena).

It is therefore archived here and hard-guarded below: it refuses to write
unless the existing frame.webp is already 1200x905, i.e. unless the project
has genuinely been rolled back to the V1 art. There is deliberately no
override flag.

It is also no longer reproducible as-is: its source layers were exported from
design-lab/nimball-designlab-current.xcf, and design-lab/ is gitignored.

--- original V1 docstring below ---

One-off bake of the new arena composite (ice + field lines + wood ring/tail
+ goal bars + scoreboard plaque) into a single 1200x905 image, replacing
public/arena/frame.webp.

The source layers in design/arena/xcf-*.png are flattened exports straight out
of design-lab/nimball-designlab-current.xcf (the actual validated design-lab
session file — extracted via the `gimpformats` PyPI package, since neither
Pillow nor GIMP itself is available here) rather than hand-reconstructed: an
earlier version of this script recomputed the ice/wood/tail/lines from
individual pre-blend source assets and a from-scratch alignment/shadow model,
which drifted from what was actually validated in the lab (stale corner
cropping, a stale pre-notch tail-shadow source, wrong intensity). Compositing
these 5 already-correct flattened layers is far more faithful — this script
now just places them, it doesn't recreate their content.

Each xcf-*.png keeps its original bounding box from the 2560x1600 .xcf canvas
(offsets noted below, read via layer.xOffset/yOffset at extraction time). The
transform to this project's fixed 1200x905/FX0..FY1 canvas is a single
uniform scale + origin shift, anchored on the "fallback fill" layer's rect
(628, 438, 1306, 724 in xcf-space) — the exact physics-box equivalent in that
file, whose aspect (1306/724=1.8039) matches FX0..FY1's own (887/492=1.8028)
to within 0.06%, confirming it's the same rect the physics box was designed
against. Re-run (`python3 scripts/bake_arena.py`) after re-exporting any of
the xcf-*.png layers from a newer .xcf; needs Pillow (`pip install pillow`).
"""
import os
import sys

from PIL import Image

ASSETS = "design/arena"
OUT = "public/arena/frame.webp"

W, H = 1200, 905


def _refuse_to_clobber_production():
    """Hard guard — see the module docstring. Bails out BEFORE any compositing
    work if the frame.webp already on disk isn't the V1 size this script
    produces, which is the signal that it would be destroying newer art.
    Deliberately no --force: if the V1 pipeline is ever genuinely revived, the
    right move is to restore the V1 frame.webp first, not to bypass this."""
    if not os.path.exists(OUT):
        sys.exit(
            f"refusing to run: {OUT} does not exist.\n"
            "This archived V1 script is not how the current arena is generated."
        )
    with Image.open(OUT) as existing:
        size = existing.size
    if size != (W, H):
        sys.exit(
            f"REFUSING TO RUN — this would destroy the production arena.\n"
            f"  {OUT} is currently {size[0]}x{size[1]} (the V2 art).\n"
            f"  This archived V1 script only produces {W}x{H}.\n"
            "See scripts/archive/bake_arena.py's docstring; the current arena is\n"
            "built by the V2 pipeline (scripts/bake_curling_arena.py + the\n"
            "upscale step), not by this file."
        )


_refuse_to_clobber_production()
FX0, FY0, FX1, FY1 = 159, 206, 1046, 698
PW, PH = FX1 - FX0, FY1 - FY0

# xcf-space physics-box-equivalent rect (the "fallback fill" layer's bounds)
XCF_BOX_X, XCF_BOX_Y, XCF_BOX_W, XCF_BOX_H = 628, 438, 1306, 724
SCALE = PW / XCF_BOX_W  # == 492/724 to within 0.06%, see module docstring

# name -> (xOffset, yOffset) in the source .xcf, as extracted from the layer
LAYERS_BOTTOM_TO_TOP = [
    ("xcf-terrain.png", (574, 410)),           # ice, already 108%-cropped + corner fallback
    ("xcf-poutres.png", (268, 244)),           # wood ring + "liant" frost tail, already blended
    ("xcf-field-lines.png", (628, 440)),
    ("xcf-tableau-score-bois.png", (1006, 244)),
    ("xcf-bordures-buts.png", (16, 64)),       # goal posts, topmost
]


def to_canvas(xcf_x, xcf_y):
    return (
        round(FX0 + (xcf_x - XCF_BOX_X) * SCALE),
        round(FY0 + (xcf_y - XCF_BOX_Y) * SCALE),
    )


canvas = Image.new("RGBA", (W, H), (0, 0, 0, 0))

for name, (ox, oy) in LAYERS_BOTTOM_TO_TOP:
    layer = Image.open(f"{ASSETS}/{name}").convert("RGBA")
    resized = layer.resize((round(layer.width * SCALE), round(layer.height * SCALE)), Image.LANCZOS)
    canvas.alpha_composite(resized, to_canvas(ox, oy))

canvas.save(OUT, "WEBP", quality=90, method=6)
print("saved", OUT, canvas.size)
